"""Core tracing primitives for AgentLane."""

from ._create import (
    agent_span,
    custom_span,
    function_span,
    generation_span,
    get_current_span,
    get_current_trace,
    trace,
)
from ._metrics import (
    AggregatedMetric,
    AggregationType,
    AvgAggregator,
    CountAggregator,
    FirstAggregator,
    LastAggregator,
    MaxAggregator,
    MetricAggregator,
    MetricRecord,
    MetricsCollector,
    MetricsRegistry,
    MetricValue,
    MinAggregator,
    SumAggregator,
    add_aggregator,
    clear_all_collectors,
    emit_metric,
    emit_metrics,
    get_aggregator,
    get_aggregators,
    get_collector,
    get_metrics_registry,
    peek_collector,
    remove_collector,
    reset_metrics_registry,
    set_metrics_registry,
)
from ._metrics_processor import MetricsProcessor
from ._processor_interface import TracingProcessor
from ._propagation import (
    adopt_parent_context,
    capture_parent_context,
    discard_parent_context,
)
from ._provider import DefaultTraceProvider, TraceProvider
from ._setup import get_trace_provider, set_trace_provider
from ._span import Span, SpanError
from ._span_data import (
    AgentSpanData,
    CustomSpanData,
    FunctionSpanData,
    GenerationSpanData,
    SpanData,
)
from ._trace import Trace

__all__ = [
    "DefaultTraceProvider",
    "TraceProvider",
    "set_trace_provider",
    "get_trace_provider",
    "Trace",
    "Span",
    "trace",
    "get_current_trace",
    "get_current_span",
    "agent_span",
    "function_span",
    "generation_span",
    "custom_span",
    "adopt_parent_context",
    "capture_parent_context",
    "discard_parent_context",
    "TracingProcessor",
    "MetricsProcessor",
    "SpanError",
    "SpanData",
    "AgentSpanData",
    "FunctionSpanData",
    "GenerationSpanData",
    "CustomSpanData",
    "MetricValue",
    "MetricRecord",
    "AggregatedMetric",
    "AggregationType",
    "MetricAggregator",
    "SumAggregator",
    "CountAggregator",
    "AvgAggregator",
    "MinAggregator",
    "MaxAggregator",
    "FirstAggregator",
    "LastAggregator",
    "get_aggregators",
    "get_aggregator",
    "add_aggregator",
    "MetricsCollector",
    "get_collector",
    "peek_collector",
    "remove_collector",
    "clear_all_collectors",
    "MetricsRegistry",
    "get_metrics_registry",
    "set_metrics_registry",
    "reset_metrics_registry",
    "emit_metric",
    "emit_metrics",
]
