"""Local process bridge for TypeScript apps hosting Python AgentLane agents."""

from ._backend import (
    BRIDGE_COMMAND_HANDLERS,
    AgentRuntime,
    BridgeBackend,
    BridgeCommandBackend,
    BridgeCommandHandler,
    ConfigRejectedError,
    ReadyMetadataProvider,
    RuntimeConfigStore,
)
from ._protocol import (
    BRIDGE_EVENT_TYPES,
    COMMAND_TYPES,
    ApproveCommand,
    BridgeCommand,
    BridgeEventType,
    CancelCommand,
    ConfigureCommand,
    ContractPayloadError,
    EventWriter,
    PromptCommand,
    ProtocolError,
    ResetCommand,
    ShutdownCommand,
    UnknownCommand,
    parse_command_line,
)
from ._stdio import AgentBackend, configure_stderr_logging, run_stdio, serve_stdio

__all__ = [
    "AgentRuntime",
    "AgentBackend",
    "ApproveCommand",
    "BRIDGE_EVENT_TYPES",
    "BRIDGE_COMMAND_HANDLERS",
    "BridgeBackend",
    "BridgeCommand",
    "BridgeCommandBackend",
    "BridgeCommandHandler",
    "BridgeEventType",
    "CancelCommand",
    "COMMAND_TYPES",
    "ConfigureCommand",
    "ConfigRejectedError",
    "ContractPayloadError",
    "EventWriter",
    "PromptCommand",
    "ProtocolError",
    "ReadyMetadataProvider",
    "ResetCommand",
    "RuntimeConfigStore",
    "ShutdownCommand",
    "UnknownCommand",
    "configure_stderr_logging",
    "parse_command_line",
    "run_stdio",
    "serve_stdio",
]
